package com.amr_medhat_r.dentale_commerceapp.utilities

object Constants {
    // Collections names in Cloud FireStore.
    const val USERS: String = "users"
    const val PRODUCTS: String = "products"
    const val CART_ITEMS: String = "cart_items"
    const val ADDRESSES: String = "addresses"
    const val ORDERS: String = "orders"
    const val FAVORITES: String = "favorites"

    const val EC_Buy_PREFERENCES = "EC_Buy_Prefs"
    const val LOGGED_IN_USERNAME = "logged_in-username"
    const val EXTRA_USER_DETAILS = "extra_user_details"
    const val KEY_IS_SIGNED_IN = "isSignedIn"
    const val KEY_LANGUAGE_ENGLISH = "en"
    const val KEY_LANGUAGE_ARABIC = "ar"
    const val KEY_RESPONSE_STATE = "status"
    const val KEY_RESPONSE_VALUE = "value"
    const val FIRST_NAME: String = "firstName"
    const val LAST_NAME: String = "lastName"
    const val MALE: String = "Male"
    const val FEMALE: String = "Female"
    const val MOBILE: String = "mobile"
    const val GENDER: String = "gender"
    const val IMAGE: String = "image"
    const val COMPLETE_PROFILE: String = "profileCompleted"
    const val USER_PROFILE_IMAGE: String = "user_profile_image"
    const val PRODUCT: String = "product"
    const val EXTRA_PRODUCT_OWNER_ID: String = "extra_product_owner_id"
    const val DEFAULT_CART_QUANTITY: String = "1"
    const val USER_ID: String = "user_id"
    const val PRODUCT_ID: String = "product_id"
    const val CART_QUANTITY: String = "cart_quantity"
    const val EXTRA_SELECT_ADDRESS: String = "extra_select_address"
    const val EXTRA_ADDRESS_DETAILS: String = "AddressDetails"
    const val HOME: String = "Home"
    const val OFFICE: String = "Office"
    const val OTHER: String = "other"
    const val ADD_ADDRESS_REQUEST_CODE: Int = 10
    const val EXTRA_SELECTED_ADDRESS: String = "extra_selected_address"
    const val STOCK_QUANTITY: String = "stock_quantity"
    const val EXTRA_MY_ORDER_DETAILS: String = "extra_my_order_details"
    const val IMAGE_TRANSITION: String = "imageTransition"
    const val TITLE_TRANSITION: String = "titleTransition"
    const val PRICE_TRANSITION: String = "priceTransition"
}